#!/bin/bash

set -o errexit

[[ $( command -v xxhsum ) ]] || { echo error: xxhsum required; exit 1; }

cd /a/local/data
find . -type f -print0 | xargs -0 xxhsum > /a/local/data_index.txt
code --diff /a/data/index.txt /a/local/data_index.txt
