field( float3, ambient_0,   color )
field( float3, ambient_1,   color )
field( float3, direction_0, color )
field( float3, color_0,     color )
field( float3, direction_1, color )
field( float3, color_1,     color )
